### ISSUE TITLE
error

### ISSUE THREAD

**Issue by axalight** [muaaz-ur-habibi/termatus#1]
File "C:\Users\Ivan\termatus\termatus\main.py", line 427, in <module>
    with Live(renderable=base(information_dictionary=basic_info(),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ivan\termatus\termatus\main.py", line 271, in base
    f"\n{cleaned_net_info[0]}\narea: {cleaned_net_info[1].split(': ')[1]}, {cleaned_net_info[2].split(': ')[1]}, {cleaned_net_info[3].split(': ')[1]}\nISP: {cleaned_net_info[6].split(': ')[1]}",
                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by muaaz-ur-habibi** [comment]
i think this part requires an internet connection in order to get the
required details. did you check your net? do tell if any other problems
occur
